### ISSUE TITLE
feature request: bruteforce decrypting option

### ISSUE THREAD

**Issue by merrychrishna** [aboood40091/SharcEditor#1]
hey can you please add a bruteforce decrypting option for when the files are encrypted?
![image](https://user-images.githubusercontent.com/59185469/177020582-ca3f5ac6-7436-47a3-a6f6-d926c760a6bd.png)

**Comment by merrychrishna** [comment]
![image](https://user-images.githubusercontent.com/59185469/177020627-979e1be4-251e-449a-962e-7f617da9c36f.png)

**Comment by aboood40091** [comment]
I believe you have mistaken this tool for something else.
This tool is for editing sharc files from the game New Super Mario Bros. U.

**Comment by merrychrishna** [comment]
I wanted to use it to decrypt files for the game PlayStation Home on PS3

**Comment by merrychrishna** [comment]
@aboood40091 you were right. i had your tool confused with this https://github.com/k0dai/sharc


but there are sharc files in the game called playstation home for playstation 3 too. could your tool be modified to extract those too?
